<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ConfigurableRejuv</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	<Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DeadworksManaged.Api">
      <HintPath>B:\SteamLibrary\steamapps\common\Deadlock\game\bin\win64\managed\DeadworksManaged.Api.dll</HintPath>
    </Reference>
    <Reference Include="Google.Protobuf">
      <HintPath>B:\SteamLibrary\steamapps\common\Deadlock\game\bin\win64\managed\Google.Protobuf.dll</HintPath>
    </Reference>
  </ItemGroup>

	<Target Name="DeployToGame" AfterTargets="Build">
		<ItemGroup>
			<DeployFiles Include="$(TargetDir)$(TargetName).dll;$(TargetDir)$(TargetName).pdb" />
		</ItemGroup>
		<Copy
		  SourceFiles="@(DeployFiles)"
		  DestinationFolder="B:\Games\steamcmd\my_deadworks_server\game\bin\win64\managed\plugins"
		  SkipUnchangedFiles="false"
		  Retries="0"
		  ContinueOnError="WarnAndContinue" />
	</Target>
</Project>